version: '3.3'
services:
  dbserver:
    image: postgres:17.5-alpine3.22
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "c:/db-postrges:/var/lib/postgresql/data/pgdata"
    ports:
      - "5435:5432"
    expose:
      - 5432
  consul:
    image: consul:1.15.4
    command: |
      agent -dev
      -ui
      -bind 0.0.0.0
      -client 0.0.0.0
    ports:
      - "8500:8500"
    expose:
      - 8500

  authors:
    image: j0hnfe/app-authors:latest
    environment:
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://dbserver:5432/postgres
      QUARKUS_DATASOURCE_HTTP_PORT: 8080
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
    ports:
      - "7070:8080"
    depends_on:
      - dbserver
      - consul
  books:
    image: j0hnfe/app-books:latest
    environment:
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://dbserver:5432/postgres
      QUARKUS_DATASOURCE_HTTP_PORT: 8080
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
    ports:
      - "9090:8080"
    depends_on:
      - dbserver
      - consul
