apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-customers
  labels:
    app: app-customers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-customers
  template:
    metadata:
      labels:
        app: app-customers
    spec:
      containers:
        - name: app-customers
          image: j0hnfe/app-customers:latest
          env:
            - name: QUARKUS_DATASOURCE_USERNAME
              value: postgres
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: postgres
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: jdbc:postgresql://distribuida-db.camtpq9odqbt.us-east-1.rds.amazonaws.com/distribuida
            - name: QUARKUS_HTTP_PORT
              value: "8080"
            - name: CONSUL_HOST
              value: consul
            - name: CONSUL_PORT
              value: "8500"
            - name: QUARKUS_FLYWAY_ACTIVATE
              value: "true"
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"


---
apiVersion: v1
kind: Service
metadata:
  name: app-customers-service
spec:
  type: ClusterIP
  selector:
    app: app-customers
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-customers-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-customers
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50